### ISSUE TITLE
User can not [Share draft] a draft session that he opened from a link

### ISSUE THREAD

**Issue by TacoByte** [kamy22/skytransfer#43]
After opening a draft session that was shared with them, the [Share draft] button is not clickable. So, the user can not share the draft session again with another user.

In practice, the user could simply copy and paste the link he originally received from the session creator, but the user should also be able to click the Share draft button to copy the link in the clipboard.

**Comment by kamy22** [comment]
@TacoByte should be solved. Please double-check it :)

**Comment by TacoByte** [comment]
Fix confirmed
