### ISSUE TITLE
Stuck on "Sync in progress..." after trying to upload lots of files

### ISSUE THREAD

**Issue by TacoByte** [kamy22/skytransfer#46]
Try uploading something like 50 files, for example 50 images, either by uploading them as files or as a directory.

After uploading every file, the uploader remains stuck on "Sync in progress...". The popup with the QR code never shows up. Trying to Share or Share draft creates a link that leads to a non updated version of the session.

**Comment by TacoByte** [comment]
I found this bug while using the siasky.net portal.

I tried replicating it on the skyportal.xyz portal, but I wasn't able to.

It seems that this bug was possibly due to siasky.net not functioning perfectly.

This means this bug depends on the portal not functioning correctly, and the application needs to know how to handle this better.

**Comment by kamy22** [comment]
@TacoByte should be fixed as part of https://github.com/kamy22/skytransfer/pull/51
