### ISSUE TITLE
Enable deletion of files

### ISSUE THREAD

**Issue by 0michalsokolowski0** [kamy22/skytransfer#59]

**Comment by ihubgit** [comment]
Hi, this seems like an obvious feature indeed. This means that all my uploaded files (even chunked and encrypted) are actually persistent on the blockchain? Could you indicate an ETA for the ability to delete files ?

**Comment by kamy22** [comment]
Hi @ihubgit. 

Actually, portals don't allow deleting files. We can delete the file from skydb index (don't display it in the file list) but the physical file will remain until the file is unpinned. Skynet added accounts. I think in the future there will be the possibility of unpinning files, we need to wait.

However, despite having the file, without having the password for the decryption, it is practically impossible to access its content as the password used is very strong.

**Comment by 0michalsokolowski0** [comment]
How do we want to display it? As far as I understand Ant Design's DirectoryTree does not support custom lines (nodes) which means we cannot create buttons on the right of the Tree as I initially expected.

**Comment by ihubgit** [comment]
hi thx for the feedback. Does this mean there would be a way to delete files when not using the portals ? If so, how ? The password you're talking about is the alphanumeric 'gibberish' after the slash of the link to the file, right ?

**Comment by kamy22** [comment]
@ihubgit 

> hi thx for the feedback. Does this mean there would be a way to delete files when not using the portals? If so, how?

In general the rule is: _skyfiles will be deleted when no one is pinning them anymore. As long as one person/node/portal is pinning the skyfile it will stay available._

Using a Sia node you can unpin the file: https://support.siasky.net/key-concepts/skynet-portals/using-a-sia-node-as-a-portal#unpin. This should work if no other nodes have pinned the file.

> The password you're talking about is the alphanumeric 'gibberish' after the slash of the link to the file, right?

A SkyTransfer link looks like: skytransfer.hns.siasky.net/{PUBLIC_KEY/PRIVATE_KEY}/{ENCRYPTION_KEY}/

Sharing a draft, a randomly generated PRIVATE_KEY is added to the link. Sharing a read-only list of files, a randomly generated PUBLIC_KEY is used. The last parameter after the slash is the ENCRYPTION_KEY, something like: **a9b2a42dc59d01cc2b31b53fbba736c3eece2f1450144e9f2c6337d297359a1b9b0135b8d73aefe41bbbfe4bb76a5086174f7fe5f2f32ba953a10abf24ae0521**

At the end you have a link similar to this one: https://skytransfer.hns.siasky.net/#/17719247bf63112cf5e72658997ad9dbc23dc2b389a5913b7edc927bad062a73/a9b2a42dc59d01cc2b31b53fbba736c3eece2f1450144e9f2c6337d297359a1b9b0135b8d73aefe41bbbfe4bb76a5086174f7fe5f2f32ba953a10abf24ae0521
