### ISSUE TITLE
Change portal name to more descriptive element

### ISSUE THREAD

**Issue by digitalblossom** [kamy22/skytransfer#61]
For example, an icon could be added before it and a little arrow behind to indicate that it is changeable, because otherwise it looks like a redirecting link

Mockup:

![image](https://user-images.githubusercontent.com/80636305/116821236-604d4000-ab79-11eb-8ba0-3a25f90dfa8a.png)

(in case you are going to implement it and want to use the icon, it is adapted from two akar icons, which is open source and has an MIT license)

> [icon as svg](https://skyportal.xyz/AAD3za3EqBDYvvN3nBmfSWx0ZcNA3DK0xj9Ny_w42Isk6g)

**Comment by kamy22** [comment]
> Change portal name to more descriptive element.

@0michalsokolowski0 this sounds like a great idea - I think we should implement it.

@digitalblossom thanks for sharing it with us!

**Comment by digitalblossom** [comment]
> > Change portal name to more descriptive element.
> 
> @0michalsokolowski0 this sounds like a great idea - I think we should implement it.
> 
> @digitalblossom thanks for sharing it with us!

any time, thanks for making such an awesome tool!
