### ISSUE TITLE
question about deletion of files

### ISSUE THREAD

**Issue by ihubgit** [kamy22/skytransfer#70]
Hi, latest version allows for deletion of files from the Sia network. That means that the end user can do this, even though normally the Sia portals pin files for 90 days minimum ? If so, deleting a file after it was downloaded will totally erase the file itself from the network and not just the pointers to it ?

**Comment by kamy22** [comment]
@ihubgit As explained in https://github.com/kamy22/skytransfer/issues/59#issuecomment-831127948, the file is deleted only from the SkyDB index. It is hidden but still in the network.
