### ISSUE TITLE
Date next to the uploaded files

### ISSUE THREAD

**Issue by stealthx** [kamy22/skytransfer#86]
Would it be possible to add date with time, next to the each file, when was the file uploaded? When another person will update my shared file, I will see that the date changed and file was updated.

**Comment by kamy22** [comment]
@stealthx we will work on it in the next few days. Thanks for sharing the idea :)

**Comment by kamy22** [comment]
![Screenshot 2021-07-09 at 14 58 45](https://user-images.githubusercontent.com/1657091/125081525-65bd8e00-e0c6-11eb-9d40-d22e13dcf6ea.png)

You should display a piece of information like that once you hover over the filename. @stealthx

**Comment by stealthx** [comment]
Thank you, it is great improvement!
