### ISSUE TITLE
Implement a popup/warning when pressing New draft button 

### ISSUE THREAD

**Issue by TootooSE** [kamy22/skytransfer#87]
When you press "New draft" and clear out the draft in progress there's no warning that the previous work you've done will be lost. If you've spent a lot of time uploading and gone through the encryption, it can be a bit disheartening if you misclick and have to re-do everything again. Maybe a simple popup telling you the new draft will replace the old one would be a good idea?

**Comment by kamy22** [comment]
@TootooSE thanks for submitting the issue. I deployed a new version with a new draft popup warning. Please refresh and let us know if it works.
